[package]
authors.workspace = true
edition.workspace = true
name = "kellnr"
version = "0.1.0"

[dependencies]
# Internal dependencies from Kellnr
common.workspace = true
db.workspace = true
derive_jsonresponder.workspace = true
docs.workspace = true
index.workspace = true
json_payload.workspace = true
settings.workspace = true
web_ui.workspace = true
registry.workspace = true
entity.workspace = true
pg_testcontainer.workspace = true
appstate.workspace = true

# External dependencies from crates.io
rocket.workspace = true
rocket_cors.workspace = true
sysinfo.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
flume.workspace = true
axum.workspace = true
axum-extra.workspace = true
openssl = {version = "*", optional = true} # Not needed directly but for cross-compilation with the vendored-openssl feature


[features]
vendored-openssl = ["openssl/vendored"]
