[package]
name = "entity"
version = "0.1.0"
edition.workspace = true
publish = false

[lib]
name = "entity"
path = "src/lib.rs"

[dependencies]
sea-orm.workspace = true
sea-query.workspace = true
sea-query-derive.workspace = true
