[package]
name = "appstate"
authors.workspace = true
edition.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Internal dependencies
db.workspace = true
settings.workspace = true
registry.workspace = true
index.workspace = true

# External dependencies
axum.workspace = true
axum-extra.workspace = true
