[package]
name = "common"
version = "0.1.0"
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Internal dependencies from Kellnr
derive_jsonresponder.workspace = true
json_payload.workspace = true

# External dependencies from crates.io
anyhow.workspace = true
serde.workspace = true
semver.workspace = true
regex.workspace = true
serde_json.workspace = true
mockall.workspace = true
rand.workspace = true
sea-orm.workspace = true
sea-query-derive.workspace = true
tracing.workspace = true
axum.workspace = true
