[package]
name = "error"
authors.workspace = true
edition.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Internal dependencies
common.workspace = true
json_payload.workspace = true
db.workspace = true
derive_jsonresponder.workspace = true

# External dependencies
zip.workspace = true
rocket.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
